//! Compile-time Fluent identifiers for derived command-line surfaces.
//!
//! `#[derive(OrthoConfig)]` emits an `OrthoConfigLocalization` implementation
//! whose associated constants are the exact Fluent identifiers the runtime
//! localizer (`LocalizeCmd`) will look up for the deriving struct. Application
//! code and tests refer to identifiers by constant instead of string
//! concatenation, and pass `T::LOCALIZATION_BASE` to `with_base`, making the
//! derive the single source of truth for the catalogue root.

/// Fluent identifiers for one argument of a derived command-line surface.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ArgLocalizationIds {
    /// The argument's clap id (explicit `#[arg(id = "…")]` or the
    /// kebab-cased field name).
    pub name: &'static str,
    /// Identifier for the argument's `help` text.
    pub help_id: &'static str,
    /// Identifier for `long_help`.
    pub long_help_id: &'static str,
    /// Identifier for the value name placeholder.
    pub value_name_id: &'static str,
}

/// Compile-time Fluent identifiers for a derived command-line surface.
///
/// Implementations are generated by `#[derive(OrthoConfig)]`. Hand-written
/// implementations are permitted for hand-built clap trees that want the same
/// compile-time identifiers.
///
/// # Examples
///
/// ```rust
/// use clap::Command;
/// use ortho_config::{ArgLocalizationIds, LocalizeCmd, NoOpLocalizer,
/// OrthoConfigLocalization};
///
/// struct DemoCli;
///
/// impl OrthoConfigLocalization for DemoCli {
///     const LOCALIZATION_BASE: &'static str = "acme.demo";
///     const ABOUT_ID: &'static str = "acme-demo-about";
///     const LONG_ABOUT_ID: &'static str = "acme-demo-long_about";
///     const USAGE_ID: &'static str = "acme-demo-usage";
///     const VERSION_ID: &'static str = "acme-demo-version";
///     const LONG_VERSION_ID: &'static str = "acme-demo-long_version";
///     const AFTER_HELP_ID: &'static str = "acme-demo-after_help";
///     const AFTER_LONG_HELP_ID: &'static str = "acme-demo-after_long_help";
///     const ARG_IDS: &'static [ArgLocalizationIds] = &[];
/// }
///
/// let command = Command::new("demo")
///     .with_base(DemoCli::LOCALIZATION_BASE)
///     .localize(&NoOpLocalizer::new());
/// assert_eq!(command.get_name(), "demo");
/// ```
pub trait OrthoConfigLocalization {
    /// The catalogue base as a dotted path, for `with_base`.
    const LOCALIZATION_BASE: &'static str;
    /// Identifier for the command's `about` text.
    const ABOUT_ID: &'static str;
    /// Identifier for `long_about`.
    const LONG_ABOUT_ID: &'static str;
    /// Identifier for the override usage string.
    const USAGE_ID: &'static str;
    /// Identifier for `version`.
    const VERSION_ID: &'static str;
    /// Identifier for `long_version`.
    const LONG_VERSION_ID: &'static str;
    /// Identifier for `after_help`.
    const AFTER_HELP_ID: &'static str;
    /// Identifier for `after_long_help`.
    const AFTER_LONG_HELP_ID: &'static str;
    /// Identifier records for every own argument, in declaration order.
    /// Flattened fields are excluded (see `docs/cli-localization-design.md`
    /// §8.2): the flattened type is expected to carry its own
    /// `OrthoConfigLocalization` implementation.
    const ARG_IDS: &'static [ArgLocalizationIds];
}

#[cfg(test)]
mod tests {
    //! Round-trip and agreement tests for the compile-time localization ids.

    use super::*;
    use crate::langid;
    use crate::localizer::{FluentLocalizer, Localizer, message_id_for};
    use rstest::rstest;

    struct HandwrittenCli;

    impl OrthoConfigLocalization for HandwrittenCli {
        const LOCALIZATION_BASE: &'static str = "hello_world.cli";
        const ABOUT_ID: &'static str = "hello_world-cli-about";
        const LONG_ABOUT_ID: &'static str = "hello_world-cli-long_about";
        const USAGE_ID: &'static str = "hello_world-cli-usage";
        const VERSION_ID: &'static str = "hello_world-cli-version";
        const LONG_VERSION_ID: &'static str = "hello_world-cli-long_version";
        const AFTER_HELP_ID: &'static str = "hello_world-cli-after_help";
        const AFTER_LONG_HELP_ID: &'static str = "hello_world-cli-after_long_help";
        const ARG_IDS: &'static [ArgLocalizationIds] = &[ArgLocalizationIds {
            name: "recipient",
            help_id: "hello_world-cli-args-recipient-help",
            long_help_id: "hello_world-cli-args-recipient-long_help",
            value_name_id: "hello_world-cli-args-recipient-value_name",
        }];
    }

    #[rstest]
    fn command_constants_agree_with_message_id_for() {
        let base = HandwrittenCli::LOCALIZATION_BASE
            .split('.')
            .collect::<Vec<_>>();
        assert_eq!(HandwrittenCli::ABOUT_ID, message_id_for(&base, "about"));
        assert_eq!(
            HandwrittenCli::LONG_ABOUT_ID,
            message_id_for(&base, "long_about")
        );
        assert_eq!(HandwrittenCli::USAGE_ID, message_id_for(&base, "usage"));
        assert_eq!(HandwrittenCli::VERSION_ID, message_id_for(&base, "version"));
        assert_eq!(
            HandwrittenCli::LONG_VERSION_ID,
            message_id_for(&base, "long_version")
        );
        assert_eq!(
            HandwrittenCli::AFTER_HELP_ID,
            message_id_for(&base, "after_help")
        );
        assert_eq!(
            HandwrittenCli::AFTER_LONG_HELP_ID,
            message_id_for(&base, "after_long_help")
        );
    }

    #[rstest]
    fn argument_constants_agree_with_message_id_for() {
        let base = HandwrittenCli::LOCALIZATION_BASE
            .split('.')
            .collect::<Vec<_>>();
        let Some(arg) = HandwrittenCli::ARG_IDS.first() else {
            panic!("ARG_IDS should contain the recipient argument");
        };
        assert_eq!(arg.help_id, message_id_for(&base, "args.recipient.help"));
        assert_eq!(
            arg.long_help_id,
            message_id_for(&base, "args.recipient.long_help")
        );
        assert_eq!(
            arg.value_name_id,
            message_id_for(&base, "args.recipient.value_name")
        );
    }

    #[rstest]
    fn constants_round_trip_through_fluent_localizer() {
        let Some(recipient) = HandwrittenCli::ARG_IDS.first() else {
            panic!("ARG_IDS should contain the recipient argument");
        };
        let localizer = FluentLocalizer::builder(langid!("en-US"))
            .with_consumer_resources([
                "hello_world-cli-about = Greet the world",
                "hello_world-cli-args-recipient-help = Who to greet",
            ])
            .try_build()
            .expect("catalogue should build");

        assert_eq!(
            localizer.lookup(HandwrittenCli::ABOUT_ID, None).as_deref(),
            Some("Greet the world")
        );
        assert_eq!(
            localizer.lookup(recipient.help_id, None).as_deref(),
            Some("Who to greet")
        );
        assert!(localizer.lookup(HandwrittenCli::USAGE_ID, None).is_none());
    }
}
