//! Code generation entry points for the derive system.
//!
//! Re-exports declarative merge emitters along with struct and trait
//! generators so the macro entrypoint can assemble complete outputs while
//! keeping the implementation cohesive.

pub(crate) mod declarative;
pub(crate) mod docs;
pub(crate) mod ortho_impl;
pub(crate) mod structs;

use syn::Ident;

/// Build a standard doc string for generated support structs.
pub(crate) fn generated_doc(config_ident: &Ident, role: &str) -> String {
    format!("{role} generated by `OrthoConfig` for `{config_ident}`.")
}
